### ISSUE TITLE
[code] background color in catalog

### ISSUE THREAD

**Issue by ccd0** [nebukazar/OneeChan#42]
I recently added the background color to [code] tags in the catalog:
https://github.com/ccd0/4chan-x/issues/263
It's in the beta version (v1.9.19.0) now.
It will need to be overridden in OneeChan, especially in the dark themes which currently turn out like this:
![screenshot from 2015-01-03 16 59 26](https://cloud.githubusercontent.com/assets/5894749/5604323/9b715956-936a-11e4-819d-baa203d5f863.png)

**Comment by nebukazar** [comment]
Small fix.

**Comment by ccd0** [comment]
Seems to be working, thanks.
