### ISSUE TITLE
"Hide Mascots in Catalog" with in ccd0's 4chan X catalog

### ISSUE THREAD

**Issue by SunnySanity** [nebukazar/OneeChan#45]
I am using the latest version of Oneechan and ccd0's 4chan X.

With JSON navigation and 4chan X catalog enabled in the 4chan X settings, the "Hide Mascots in Catalog" option in the Oneechan settings continues to display a mascot in the 4chan X catalog (the option does not change anything).

Please tell me if you can replicate this issue.

**Comment by nebukazar** [comment]
Tell me if this works for you.

**Comment by SunnySanity** [comment]
Nope, still see the mascot on the catalog page after updating Oneechan, refreshing the page, and restarting the browser.

I'm clicking the [Catalog] button on the top left of the page. Here are my relevant 4chan X settings.
![4chanxsettings](https://cloud.githubusercontent.com/assets/10573069/5790237/575da92e-9e5d-11e4-806c-65adc2d6e36f.png)

**Comment by nebukazar** [comment]
This is working now.
