### ISSUE TITLE
Bottom ad isn't affected by ad settings.

### ISSUE THREAD

**Issue by dck-k** [nebukazar/OneeChan#46]
As long as any advertisement is enabled, the bottom ad always shows up regardless of whether it's selected or not.
Firefox version 35.0 and Oneechan version 5.5.15 (both latest at the moment).

**Comment by nebukazar** [comment]
Well this is weird, I don't know why it isn't hiding that ad in particular when the CSS path is actually correct. I don't care enough about ads to look more into it, so I'm just going to remove it completely.

**Comment by nebukazar** [comment]
Those ads are being added through Javascript it seems. So what I did is remove the node completely from the document when the option is disabled.
