### ISSUE TITLE
Tabbing from the comment box to the captcha brings you to the top of the page

### ISSUE THREAD

**Issue by MisakaImoutoWaifu** [nebukazar/OneeChan#48]
I'm on OS X 10.10 using Chromium 38 and the latest 4chan X.

-Try to tab from comment box to captcha

What should happen
-You go to the captcha

What happens
-You jump to the top of the page to some invisible element
-You need to press tab again to get to the captcha

**Comment by ccd0** [comment]
Which fork of 4chan X and what captcha-related settings?  (It might help to post your exported settings.)  And unless it only happens with Oneechan enabled, it's likely a 4chan X issue, not an Oneechan issue.

**Comment by MisakaImoutoWaifu** [comment]
Oops. I guess I should have checked that. I assumed it was Onee-chan but it is 4chan X. Sorry for that.
