### ISSUE TITLE
Submit button wraps to new line in loadletter fork

### ISSUE THREAD

**Issue by ccd0** [nebukazar/OneeChan#52]
Happening with 4chan X loadletter v2.40.50 and OneeChan v5.5.19, both in Firefox and Chromium.  Without OneeChan the file field and submit button are on the same line.

![screenshot from 2015-03-01 18 20 28](https://cloud.githubusercontent.com/assets/5894749/6434566/90a9fba6-c040-11e4-8cfc-75841b3bcf95.png)

**Comment by nebukazar** [comment]
You need to pick loadletter compatibility in the OneeChan settings menu (it's at the bottom).

**Comment by ccd0** [comment]
Oops, forgot about that.  It should be possible to auto-detect that, though.

**Comment by nebukazar** [comment]
I was always faced with race conditions, it detected loadletter and applied the CSS correctly but then wouldn't detect your 4chan X version correctly.
