### ISSUE TITLE
Chrome tab crash on board open

### ISSUE THREAD

**Issue by wickedwzrd** [nebukazar/OneeChan#54]
Whenever I try and open /g/ the tab keeps crashing. I have disabled every extension except for oneechan and the page will load but when I try to go into catalog the tab crashes. Having ccd0 4chanX enabled by itself will load the page perfectly. I also tried using only ccd0 then going into a thread, then enable oneeChan and reload the page. This method did not crash the tab and it was working. Any help would be greatly appreciated.

**Comment by nebukazar** [comment]
Which version of Chrome are you using? 
Have you installed Oneechan through Tampermonkey?

Oneechan is not meant to work without 4chan X but crashing the tab seems a bit weird, it should load normally.

**Comment by wickedwzrd** [comment]
Chrome Version: 41.0.2272.101
It is installed through tampermonkey and I just reinstalled as well. I never had this problem until today so I don't know what could've happened.

**Comment by nebukazar** [comment]
Any console errors (ctrl + shift + J) when you enter the catalog?
Does it only happen on /g/?

I'm unable to reproduce.

**Comment by wickedwzrd** [comment]
Tampermonkey started
core.988.js:352GET http://s.zkcdn.net/ados.js net::ERR_BLOCKED_BY_CLIENTcore.988.js:352 initAds(index):1 (anonymous function)
script.js:11392 'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).
3VM126:3 Uncaught ReferenceError: prettyPrintOne is not definedVM126:3 (anonymous function)

**Comment by wickedwzrd** [comment]
That is the error I'm getting

**Comment by wickedwzrd** [comment]
It started working again when I loaded /g/ a few seconds ago. So I'm going to close the issue.
