### ISSUE TITLE
Checkboxes not riced

### ISSUE THREAD

**Issue by sikmo** [nebukazar/OneeChan#57]
When using JSON Navigation on 4chanX , the checkboxes in the index page appear not riced like this:
![cb1](https://cloud.githubusercontent.com/assets/3687469/7747900/e9c95e04-ffc7-11e4-8cd8-70a26dcb14a2.PNG)

The issue doesn't appear when replying to a thread or when disabling JSON Navigation.
![cb2](https://cloud.githubusercontent.com/assets/3687469/7747911/0c05aebe-ffc8-11e4-8aa5-2869ce9f991a.PNG)

I'm using ccd0's 4chan v1.10.12.7 and Firefox.

**Comment by nebukazar** [comment]
Not sure what's causing this, might be some weird interaction with how 4chan X loads its own catalog. Any idea how long it's been happening?

**Comment by sikmo** [comment]
I only noticed it with v1.10.12.7. Before that I always had the checkboxes disabled so I don't really know if it was happening.

**Comment by nebukazar** [comment]
I made the original checkboxes hide by default in 5.5.32, this means no checkboxes will show up in the index but since you can't report multiple posts anyway and the 4chan X menu is better it should be no problem.

Riced checkboxes will still appear in threads.
