### ISSUE TITLE
File info doesn't always show even with "Show File Info" checked and "Show post info on hover" unchecked

### ISSUE THREAD

**Issue by steeben** [nebukazar/OneeChan#61]
I've tried every combination of those two settings and no matter what the file info (filename, size, ect.) won't show unless I mouse-over the image. This is extremely annoying because when I hover over the image, the image moves to make room for the file info.

The issue is also happening with the post number on replies. It only shows when I hover the reply's box, when I have that option apparently disabled.

![image](https://cloud.githubusercontent.com/assets/13606697/9160918/8250599a-3f04-11e5-8ec6-5d8aa4521ec7.png)

**Comment by nebukazar** [comment]
Have you checked for any custom CSS (both in your Oneechan theme and 4chan X) or if you have any styles installed that might conflict?

Could you try a reset of Oneechan to see if it still happens? Both those options seem to be working correctly for me, with ```Show Post Info On Hover``` enabled it means file info and post number will only show up when you hover the post doesn't matter what part.

**Comment by nebukazar** [comment]
Is this still happening? I think the theme you're using, Penumbra, has some CSS of its own that does the same thing as 4chan, that's likely the reason it's happening.
