### ISSUE TITLE
mitchell-netravali downscaling for mascots

### ISSUE THREAD

**Issue by Farfie** [nebukazar/OneeChan#62]
i dont know how hard it would be on the browser, but it shouldn't be too bad. i think firefox uses catmull-rom already. actually is that already being used for mascots? seems like maybe but i dunno, i dont web develop (nor have i spent any real time coding, though i went to college for it lol), but im not sure i can find a javascript implementation for m-n anyway. is there another way, or any way i can help with this?

**Comment by nebukazar** [comment]
I'm not an expert but image manipulation in browsers is traditionally done via CSS (`<img>`), and more recently through HTML5 canvas (`<canvas>`). Using canvas will likely involve more processing. You will get better up- and downscaling this way but I'm not sure it's the best thing to use for browsing 4chan considering Oneechan feels already quite heavy (at least to me) with all these CSS rules.

> actually is that already being used for mascots?

It uses the auto scaling options of the browser. [General.css#L369](https://github.com/nebukazar/OneeChan/blob/c20d5bfb5fe38a1296d55b39d97385d41f8cf63a/src/css/General.css#L369)

What are you trying to do?

**Comment by Farfie** [comment]
I was just interested in using a different scaling algorithm for images (in case you don't know there are very many, with a lot of opinions involved... I'm sure you've dabbled with madvr and whatnot yes?), but as you say it just uses whatever the browser uses by default. I wish I knew more about css, but is there a specific line of code that tells the browser the image might need scaling, or does the browser just figure out somehow that the image needs scaling and then does it? Or somehow else? I'll start looking into what Firefox uses and see if there are options via addons or something else.

**Comment by nebukazar** [comment]
I guess you're trying to apply scaling filters so that when you scale the image it retains some sort of quality?

On a webpage you will display an image through the `<img>` tag like:
```html
<div id="mascot">
<img src="https://i.imgur.com/AD18Ld2.png"></img>
</div>
```
Obviously your image will display on the page using its original dimensions, but by using CSS like this:
```css
#mascot img {
  height: 150px;
  width: 50px;
}
```
You can scale the image how you see fit and apply other CSS effects. You can read in [image-rendering](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering) that Firefox uses "bilinear resampling (high quality)". This is how mascots are scaled.

**Comment by Farfie** [comment]
Gah, I even found that page but didn't notice the line there where it said Gecko was using bilinear (yuck). I knew our kawaii little mascots didn't look /that/ high quality.

Obviously this is outside the realm of your userscript though so I don't want to continue unless you would also be interested in getting to the bottom of it. The end result would be better downscaling (or upscaling actually, bilinear is quite bad if you're unaware) of mascots on browsers where the mascot area are smaller than usual (my browser is on a monitor in portrait mode), and on modern computers I believe the hit on performance you're worrying about would be much more minimal than you're thinking. Even my phone now can practically play 1080p at 60fps, and it's an htc one original (m7).

The next step would be determining the best way to implement these scalers. I've already searched for a firefox addon to no avail that would add custom scalers for different media types and let you select one, or just come with a bunch of well known good ones, which is actually very surprising to me. I'm almost motivated to try and write one now. Maybe it's just not possible? Do you know if theres any kind of functionality in css or html5 to specify your own? I think I saw that HTML5 could even use lanczos, which would be pretty phenomenal.

**Comment by nebukazar** [comment]
I found this [stackoverflow thread](https://stackoverflow.com/questions/2303690/resizing-an-image-in-an-html5-canvas), there may be some good answer to what you're trying to achieve. Let me just say my JS knowledge is limited and I only maintain Oneechan because no one else will take it.

That being said, the original mascot images are pretty low quality. You can always replace them or get new high-res ones of course.

**Comment by Farfie** [comment]
So after a bunch of research and testing I've decided that the benefit doesn't outweigh what /I'd/ have to do to get it nice, mostly because I'd just have to do a shitload of learning in an area that hasn't ever really interested me (web development I guess). I'm surprised though that there isn't someone out there with a similar interest that already has the know-how to implement it easily, if possible. Maybe it's not easy, or maybe as you say it is too resource intensive. I guess we'll never know :(

It did make me sad though when you just said you only maintain Oneechan because no one else will take it. I know that feeling all too well, trying to find motivation to continue these kinds of things. I was very scared when whats his face first decided to drop it, I wasn't sure if anyone would pick it up, but I did think someone /probably/ would, and they did. And that leads in to what I want to say to you now: no one will tell you directly that they "want" it from you, but if you left it, rest assured that someone will probably pick it up. So you could always give up if you really wanted to, I think.

Anyway, thanks a lot for all the work you've done regardless, and trying to help me on this now silly endeavor. Believe me that even if people don't express it, they love the shit you do. It's really the only motivation there is.

**Comment by nebukazar** [comment]
Thanks for the kind words. As long as I can fix it, it's not a problem maintaining it but if something more complicated arises I'm afraid I'll be stuck.
