### ISSUE TITLE
"Show Top Links" shows bottom board list

### ISSUE THREAD

**Issue by DeckardEdward** [nebukazar/OneeChan#64]
For some reason, my bottom-of-page board list is showing when the Show Top Links option is checked. Unchecking it gets rid of the board list, but it also gets rid of the catalog controls. I used to have the catalog controls and the bottom board list was hidden, but my browser did something.

All of the details of the problem up until this point are here: https://github.com/ccd0/4chan-x/issues/500

**Comment by nebukazar** [comment]
4chan X has an option in the header menus to show or hide the bottom board list.

Unchecking `Show Top Links` in Oneechan works correctly when it hides the links at the top of the catalog list (Index / Archive / Bottom), however it should not hide the bottom board list. I have now fixed that.

Thanks.
