### ISSUE TITLE
Full catalog comments on hover

### ISSUE THREAD

**Issue by ccd0** [nebukazar/OneeChan#68]
I want to merge this into 4chan X
https://github.com/ccd0/4chan-x/compare/catalog
to show full comments in the catalog when a thread is hovered over, but it will break the catalog badly for OneeChan users unless at least the colors are overridden to match the theme.

Also, do you have any other ideas about how to make full comments visible? For example, one alternate approach would be 8chan's scroll bars which are toggled by a click.

**Comment by ccd0** [comment]
> For example, one alternate approach would be 8chan's scroll bars which are toggled by a click.

Also
https://github.com/ccd0/4chan-x/issues/489
is another option under consideration, although it looks like the scrollbars part was left out. It would be good to get some feedback about it.

**Comment by nebukazar** [comment]
Is this still in the works? I like the full text on hover version, scrollbars are kinda ugly.

Another solution could be to show a kind of tooltip/popup with full text, image and all the info 4chan provides about the thread when you hover it.

Example:
![untitled](https://cloud.githubusercontent.com/assets/5222254/12572771/6a0126e4-c3e8-11e5-980d-084e39b7d113.jpg)
:

**Comment by ccd0** [comment]
>Is this still in the works?

Yes, although now I think I can do it without breaking things so badly. Although I noticed a bug with the border I'll need to fix. `outline` isn't doing the same in Firefox and Chromium.

>Another solution could be to show a kind of tooltip/popup with full text, image and all the info 4chan provides about the thread when you hover it.

A tooltip would mean that you can't click links, although I agree that showing more info on hover would be good. I might also try widening the text on hover like in Infinity Next.

**Comment by ccd0** [comment]
Closing the issue here for now since I no longer need anything overridden in Oneechan in advance. The current version doesn't break things so badly. I'll reopen if/when it reaches beta.

**Comment by ccd0** [comment]
Reopening because the new catalog CSS will be in beta soon.
Also, catalog related, but an HTML change rather than a CSS change, 4chan X will be reusing the `<blockquote>`s from the post in the catalog thread as I mentioned at https://github.com/nebukazar/OneeChan/commit/1451db0c2f75902213648d472963f9a817c82576#commitcomment-19125975.

**Comment by ccd0** [comment]
On second thought, it's probably still too early to make any changes yet. I'm still considering whether to reuse a few objects from the post by moving them into the catalog thread or to change the post itself into the catalog thread by adding some elements and restyling.

**Comment by ccd0** [comment]
Catalog changes are now out on the beta channel.

https://github.com/ccd0/4chan-x/blob/master/CHANGELOG.md#v1130

As far as I know, there's nothing that breaks things to the point of unusability, but you'll probably want to set the colors for the background color of the catalog threads on hover

`:root.catalog-hover-expand .catalog-container:hover > .post`

and the border color used in various places in the catalog:

```
:root.werkTyme .catalog-thread:not(:hover),
:root.werkTyme:not(.catalog-hover-expand) .catalog-thread,
:root.catalog-hover-expand .catalog-container:hover > .post,
:root.catalog-hover-expand .catalog-container:hover .catalog-reply
```

and you may have to change various other things due to all the CSS changes on 4chan X's end.

Also, be sure to check whether things look okay in the 4chan X catalog with `Werk Tyme` enabled, because the CSS is a bit different for that case.

**Comment by nebukazar** [comment]
Thanks for the heads-up. There should be an option to disable it in the options menu (unless I missed it), people are probably going to miss the one in the header since they don't read changelogs.

**Comment by ccd0** [comment]
I found a remaining discrepancy: In the 4chan X catalog with Werk Tyme on, a highlighted thread gets the highlight from 4chan X instead of OneeChan's highlight color. Except if the thread has no file or a deleted file, in which case it gets both highlight colors, in different places.
![werktyme-highlight](https://cloud.githubusercontent.com/assets/5894749/19999363/240d8af8-a22f-11e6-81d0-c0563141e149.png)
Pic is from /news/ with `/media/;highlight` in comment filters.

**Comment by ccd0** [comment]
I still see the highlighting issue as of v5.6.1.
