### ISSUE TITLE
Oekaki interface in QR should be styled in Oneechan

### ISSUE THREAD

**Issue by ccd0** [nebukazar/OneeChan#69]
At the moment, with Oneechan, it doesn't match the rest of the buttons.  I presume this is just a matter of changing the appropriate selector.

![screenshot from 2015-11-22 14-01-40](https://cloud.githubusercontent.com/assets/5894749/11326563/b147e672-9121-11e5-93cd-f8d282086137.png)

**Comment by nebukazar** [comment]
You can't style number spinners in Firefox apparently so I'm removing them. Also fixing that captcha.

**Comment by ccd0** [comment]
The captcha is in an iframe on www.google.com, but you can ask for a "light" or "dark" theme. Currently I'm only setting it to dark if the document has the `tomorrow` class, but I could add a test for something like `dark-theme` as well. Alternatively you could run Oneechan on www.google.com. Or put filters on the iframe, but that didn't work out well for Appchan X.

**Comment by nebukazar** [comment]
>but I could add a test for something like dark-theme as well

I'd prefer this option since 4chan X already runs on www.google.com, if you don't mind.

**Comment by ccd0** [comment]
> dark-theme

Or perhaps `dark-captcha` would be better.

**Comment by ccd0** [comment]
Newest beta (v1.11.23.1) tests for `dark-captcha` in addition to `tomorrow`.
