### ISSUE TITLE
New boards need SFW/NSFW definitions

### ISSUE THREAD

**Issue by Yaanu** [nebukazar/OneeChan#71]
I don't know if "definition" is the proper term, but it seems appropriate.

Two of 4chan's newest boards, /aco/ (Adult Cartoons) and /trash/ (Off-Topic), are designated as NSFW sites. However, Oneechan fails to change its custom color scheme for those boards from SFW to NSFW.

Obviously, this is only an aesthetic issue. However, it would be nice to see a quick hotpatch or something of the sort to fix the issue.

Thank you.

**Comment by nebukazar** [comment]
Thanks.
