### ISSUE TITLE
Sidebar Appears on 4chan home page and in catalog 

### ISSUE THREAD

**Issue by TheSupremeGentleman** [nebukazar/OneeChan#72]
Despite having 'Disable in Catalog View' checked, the sidebar still appears in catalog
It also appears on the home page of 4chan and this bugs me the most.

It also seems that the midnight caek theme is not applied to all parts of the homepage as seen in the attached screenshot.
![4750ebd01503a16acbc52fc8355b659f](https://cloud.githubusercontent.com/assets/16794562/12443941/7275b2ae-bf10-11e5-842e-10993ddf7610.jpg)
![ca86dc77b2502ee8eb14d506b779597b](https://cloud.githubusercontent.com/assets/16794562/12443942/72788eca-bf10-11e5-811f-2d63084768ec.jpg)

**Comment by nebukazar** [comment]
>Despite having 'Disable in Catalog View' checked, the sidebar still appears in catalog

This option only works with the native catalog sadly.


>It also appears on the home page of 4chan and this bugs me the most.

See issue https://github.com/nebukazar/OneeChan/issues/37. I am preventing Oneechan from applying to the home page in the next version.

**Comment by ccd0** [comment]
> This option only works with the native catalog sadly.

Is there anything you need from 4chan X's end to fix it?

**Comment by nebukazar** [comment]
I have no idea, I haven't worked on Oneechan in months, it should work theoretically but it's probably the same problem as https://github.com/nebukazar/OneeChan/pull/35.

I'm just going to fix minor stuff I can fix for now.

**Comment by nebukazar** [comment]
4chanX doesn't send any event when it displays the catalog, right?

I noticed the domain doesn't change from `https://boards.4chan.org/v/` while 4chanX's catalog is showing, but with the native catalog it changes to `https://boards.4chan.org/v/catalog`.

**Comment by ccd0** [comment]
No, but it does add/remove classes from the document.
I'm thinking the easiest thing to do would be to take the JS out of https://github.com/nebukazar/OneeChan/blob/master/src/style.js and do the logic in CSS. Using LESS's [nested rules](http://lesscss.org/features/#features-overview-feature-nested-rules) could make it pretty easy to write.  You'd just have to wrap all of Sidebar.css in something like

`:root:not(.no-sidebar):not(.disable-in-catalog.catalog):not(.disable-in-catalog.catalog-mode) {`
`}`

and change each `:root` within to [`&`](http://lesscss.org/features/#parent-selectors-feature).
