### ISSUE TITLE
A question about scrolling and navigation between pages.

### ISSUE THREAD

**Issue by TheSupremeGentleman** [nebukazar/OneeChan#74]
I don't recall how I managed to do this, but whenever I navigate to the next page in the index, the next page does not reset to the top and instead is scrolled down to the same palce as on the previous page. I've looked through the settings and I am really not sure what is responsible for this. 

Any idea on what could be affecting this?

**Comment by ccd0** [comment]
Could you export and post your 4chan X and Oneechan settings?

**Comment by TheSupremeGentleman** [comment]
Here ya go:

[OneeChan v5.5.35 Settings.txt](https://github.com/nebukazar/OneeChan/files/110726/OneeChan.v5.5.35.Settings.txt)
[4chan X v1.11.22.4-1454143231928.txt](https://github.com/nebukazar/OneeChan/files/110727/4chan.X.v1.11.22.4-1454143231928.txt)

**Comment by ccd0** [comment]
Oh, and I forgot to ask, what browser?

**Comment by ccd0** [comment]
Reproduced. It's probably an OneeChan setting hiding the thing 4chan X is scrolling to.

**Comment by ccd0** [comment]
It happens when "Show Navigation Links" is turned off.

**Comment by ccd0** [comment]
I put a fix in 4chan X so people can hide the navlinks without messing up the scrolling. It should go out next beta.

**Comment by TheSupremeGentleman** [comment]
Just got the beta, and it scrolling back up on page navigation perfectly!
