### ISSUE TITLE
Putting stuff back in the sidebar

### ISSUE THREAD

**Issue by Cruxador** [nebukazar/OneeChan#75]
A lot of stuff that used to be in the sidebar some years ago is now in 4chan X's top navigation bar. That's not terrible for many purposes, but for me, since I don't aesthetically like that thing hovering over my page, it means that the data is locked to the top, or I have to make it float, which is unappealing in other regards and doesn't really integrate with the aesthetic of anything. And there's no way to make that have a transparent background, which makes it worse.

Here's how it used to be, and in my opinion how it ought to be:
![image](https://cloud.githubusercontent.com/assets/2652123/12809376/573c9bdc-cad3-11e5-92e5-880aec31ff5d.png)

**Comment by nebukazar** [comment]
Yes, that was in the old version of Oneechan when it used [4chanSS](https://github.com/nebukazar/4chan-Style-Script)'s code and 4chan X v2. That's a screen from Appchan X, although there are a few options you can work with if you still want to use 4chan X + Oneechan:

First, if you go into 4chan X's navigation bar, under that small triangle, you can select to have the bar at the bottom or automatically hiding on scroll.

![navbar01](https://cloud.githubusercontent.com/assets/5222254/12825966/be12a106-cb70-11e5-80a0-88fa5158feda.png)

Secondly, you can disable all these options in Oneechan:

![navbar02](https://cloud.githubusercontent.com/assets/5222254/12826035/0a7c89bc-cb71-11e5-8c45-a07f637f9a66.png)

Third, you can go into your Oneechan theme settings and set the Header Opacity to "0":

![navbar03](https://cloud.githubusercontent.com/assets/5222254/12826123/6c9cbe14-cb71-11e5-8469-f47de4f6cd91.png)

**Comment by Cruxador** [comment]
That works excellently, thanks!
