### ISSUE TITLE
Black boxes appear randomly

### ISSUE THREAD

**Issue by Dumbassahedratron** [nebukazar/OneeChan#77]
While scrolling through either threads or the index on any board, black boxes appear randomly. They vary in size, and I haven't found a particular way to reproduce the bug. It seems to occur when mousing over backlinks and images, however I've seen it occur whilst scrolling the main index with my mouse nowhere near a link.

OneeChan is up to date, and Firefox is version 44.0.2. I've used AppchanX and was not able to replicate this, and it occurs with both 4chan X (ccd0's fork) and 4chan X (loadletter's fork).

**Comment by Dumbassahedratron** [comment]
http://imgur.com/a/HrtKj

Github is not cooperating, otherwise I would've embedded the images. My apologies.

**Comment by Dumbassahedratron** [comment]
http://imgur.com/a/HrtKj

Github is not cooperating, otherwise I would've embedded the images. My apologies.

I'm not 100% certain that this issue is being caused by OneeChan or 4chan X, but hopefully you can shed some light on the problem or send me in the right direction.

Thanks.

**Comment by ccd0** [comment]
Have you tried disabling hardware acceleration?

**Comment by Dumbassahedratron** [comment]
My GPU doesn't support the option, or at least the option is greyed in Windows and I cannot find anything regarding hardware acceleration in the Nvidia control panel. For reference, it's a GeForce 760, and I'm running Windows 7 Ultimate 64bit.

**Comment by Dumbassahedratron** [comment]
That fixed both of the issues I had. For reference, the other issue I had was that when I used fonts like Helvetica, Lucida Grande and similar, on mouseover of backlinks or quotes characters such as "l", "|", "i", "-", "=", etc would disappear while the mouse was moving and reappear once the mouse came to a stop. 

Thanks.
