### ISSUE TITLE
/lgbt/ marked NSFW

### ISSUE THREAD

**Issue by ccd0** [nebukazar/OneeChan#78]
From https://rbt.asia/g/thread/S53461750#p53465307:

>Would anyone with a github account mind either making a new issue or editing the code itself to fix a tiny problem with OneeChan's script?

>The problem is that >>>/lgbt/ is a blue board, but it's marked as NSFW on the script. So, either telling the developer that, or editing the line 4123 of the code from /src/script.js to be

>`nsfw: /^(b|d|e|f|gif|h|hr|r|s|t|u|wg|i|ic|r9k|hm|y|hc|pol|soc|aco|s4s|trash)$/.test(pathname[0]),`

>should be fine.

>https://github.com/Nebukazar/OneeChan/issues

>https://github.com/nebukazar/OneeChan/blob/master/src/script.js#L4123

**Comment by nebukazar** [comment]
Thanks.
