### ISSUE TITLE
Downscale only mascot enhancement option

### ISSUE THREAD

**Issue by Farfie** [nebukazar/OneeChan#79]
Hey guys,

I tried to look at the code and make a pull request myself but I just can't get my head around it... I've only ever really programmed in C or Java.

I load grills with a php script that chooses an image at random from a directory. So, auto means large images will be too big for the sidebar, and 300px means smaller images will be upscaled and look terrible.

At first this seems like a fringe case, well it is, but I think that this change would also make a better default. The idea of course is to set the width to 300px by default, and add a checkbox option called "downscale only" to leave images with width <= 300 alone, and images > 300 would be downscaled to 300px. This would also be better as a default because 99% of the time people would never have to change any of the px options unless it was really tall, where now, you have to change it every time auto makes it too big.

There might even be a better way to do this, I just wanted to get the concept across and use some conceptual logic as an example. Maybe this should be the way auto intrinsically works? I dunno.

Thanks for your consideration, and as always, thanks for forking in the first place.

**Comment by nebukazar** [comment]
Hihii,

> I load grills with a php script that chooses an image at random from a directory.

If I understand this correctly, you load images into Oneechan through a remote php script/page and because you have different sizes of images that means some of them get up/downscaled due to the auto height and width settings (in Oneechan) for that php script URL?

I have no idea how many people use a kind of setup like yours but I imagine most simply put in their mascot URL and manually set the dimensions to their liking for each mascot. This means creating an entry for every single mascot.

Obviously, your setup is better if you just want to to throw a bunch of mascots into a folder and load them randomly.


> add a checkbox option called "downscale only" to leave images with width <= 300 alone, and images > 300 would be downscaled to 300px. 

If my first assumption is right, how would Oneechan know which images (and their dimensions) are being loaded into the page in this case?

**Comment by bakugo** [comment]
>If my first assumption is right, how would OneeChan know which images (and their dimensions) are being loaded into the page in this case?

I haven't used Oneechan in a while so I'm not sure, but it sounds like you're using the `width` css property to resize images. So a checkbox to use `max-width` instead should be enough.

**Comment by Farfie** [comment]
The script chooses a random image from a directory and only sends that to Oneechan, so I would imagine Oneechan can get its properties the same way it gets it from any image in an url... I guess? It's more like the script randomly chooses the url of an image and sends that to Oneechan. I am making assumptions about the code, but I don't even know if I am or not so my apologies.

And yes, as I said the use case is low, but I also believe doing this would be a better default action than the current, as any time an image is above 300px in width, people are most likely just going to set 300px in the box. With the new default behavior, when implemented correctly, you would almost never have to change anything. It would just fit into the side bar magically, unless it's a very tall image... then you would want to reduce the height ofc.

**Comment by nebukazar** [comment]
I think I got it working, should be in the next Oneechan version (5.5.41).

**Comment by Farfie** [comment]
Sorry for the late response, I only really come on Github to give ideas.
I also appreciate that you are at least trying.

Not quite. Remember that making things smaller than the sidebar is not what the option is for. It does that, and it's great (and is what makes it a great default option), but technically the aim is to make sure things that are small do not get upscaled to the sidebar in size (thus "Downscale **only**"). This is the behavior when you set the picture to be a specific 300px in size. It makes images with a lot of height compared to the width (like 5:1 when h:w) look absolutely massive in the sidebar. They would still be in the bounds horizontally, but vertically they were going into the 4chan bar on top even.

Here is an example of a very "tall" image set to 300px for width:
![vft6ms 1](https://cloud.githubusercontent.com/assets/2372953/22306757/6aa5f052-e30e-11e6-9294-fbcc753fd7b8.png)
As you can see, because it is such a tall image, the height is enormous.

With the Downscale only option, you should be able to safely leave the 300px width the same, and the mascot would still look like this:
![mlaxah 1](https://cloud.githubusercontent.com/assets/2372953/22308503/3ddf747e-e315-11e6-97da-083e11319b79.png)
Because, Downscale only was preventing the upscaling of the previous example. Also, in a perfect world, perhaps Downscale only would also center the image when its width ends up being <300px. I would think anyway. Maybe not?

Only with these two options combined do you create the ideal scenario where almost no image will be too big or too small, automatically. And of course there may be even better ways to do it, But I was trying to create less work for you, heh.

**Comment by nebukazar** [comment]
Sorry, I've been out of the loop for a while and only saw this today, I will not work on the extension much anymore as I have other interests.

However, I'm having trouble understanding what you want exactly or maybe I'm missing something. Doesn't the mascot get scaled automatically if you leave width and height on `auto` and enable `Downscale Only`? You can put in any height or width you want but with `Downscale Only` enabled the width will never change from the **max-width: 300px** rule no matter the value in the width field. 

This means that with `Downscale Only` enabled  and width=auto and height=auto:
- Images greater than 300px in width will have 300px as width and an height according to the aspect ratio.
- Images smaller than 300px in width remain unchanged.

As for the image centering you can set an horizontal offset but it's probably better to fix that in your mascots so they are all uniform.

 Hope this clarifies things.
