### ISSUE TITLE
Browser freezing randomly

### ISSUE THREAD

**Issue by DeckardEdward** [nebukazar/OneeChan#81]
Whenever I'm scrolling through a long page on 4chan for a long time, my entire browser seems to freeze randomly either while the page is scrolling or when I expand/shrink an image, and occasionally just whenever it feels like it. This happens on my laptop and my desktop.

I can't make it happen at will or to predict when it will start, so I don't really have any easy way to test whether this is stemming from 4chan X or Oneechan, but browsing for a while with Oneechan shut off seemed to work around the problem, so I opted to post the issue here. Apologies if I'm pinning this on the wrong script.

**Comment by DeckardEdward** [comment]
Update: I may be wrong about this, but it seems like the freezing problem happens more often in threads with gifs/webm's uploaded than in threads with just still images. It also seems like if I scroll often, the hangs stay short, whereas if I let the page sit for a while the hangs get unreasonably long.

**Comment by ccd0** [comment]
Do you have "Replace WEBM" turned on?

**Comment by DeckardEdward** [comment]
Nope. That's just ridiculous. I do have replace gif turned on though.

**Comment by nebukazar** [comment]
Firefox or Chrome?

I can't seem to reproduce this. Although my browser does freeze for a bit when opening really big threads. The bigger the thread the more CSS rules need to be applied...

**Comment by DeckardEdward** [comment]
I'm using Firefox. On the offchance that it may help, here's my Oneechan settings.

https://dl.dropboxusercontent.com/u/25349796/OneeChan%20v5.5.38%20Settings.json

**Comment by DeckardEdward** [comment]
Okay, so I tried switching Replace Gif off, and it's been a few days. My browser hasn't frozen for a few days at this point.

Maybe I was wrong about Replace Gif not being the root of the problem.

**Comment by nebukazar** [comment]
When  browser encounters a javascript file it stops doing everything else until it has read the file, I guess this is the limitation in using two userscripts on top of each other but things can probably be improved.
