### ISSUE TITLE
New /qst/ board formatting

### ISSUE THREAD

**Issue by nanosaur** [nebukazar/OneeChan#83]
I'm not even sure if the new board will stick around, but I thought I should at least mention it just in case.

The new board allows for various post formatting including things like italics, bold text, colored text, etc. that doesn't show up when using Onee-chan.

**Comment by ccd0** [comment]
Fix as usual should be to grab the relevant CSS from 4chan and put it in
https://github.com/nebukazar/OneeChan/blob/master/src/css/Original.css

**Comment by ccd0** [comment]
https://github.com/Floens/ChanTracking/commit/9978080b3e650310046985a4a963f25fbd8efa7e

**Comment by ccd0** [comment]
Thread for testing (I think this one uses all the tags):
http://boards.4chan.org/qst/thread/40963

**Comment by nebukazar** [comment]
Thanks.
