### ISSUE TITLE
Prefixing blink, gecko, webkit, and edge classes on document

### ISSUE THREAD

**Issue by ccd0** [nebukazar/OneeChan#85]
After 4chan changed its CSS to use `blink` for blinking, I'm prefixing the CSS classes `blink`, `gecko`, `webkit`, and `edge` classes that 4chan X adds to the document to indicate the detected browser engine with `ua-`, so that in Chrome, for example, `ua-blink` is now added to the document. I'm temporarily having 4chan X add both the old and new versions of the class names, but the old ones will be removed shortly (https://github.com/ccd0/4chan-x/issues/904).

This is probably a good time to check how many of the useragent-specific workarounds you still need.

I'm also planning on removing the `index`, `thread-view`, `catalog`, and `archive` classes since 4chan adds `is_index`, `is_catalog`, `is_arclist` to the body itself (https://github.com/ccd0/4chan-x/issues/955), but that's further into the future.

**Comment by ccd0** [comment]
I've gone ahead and removed `blink`, `gecko`, `webkit`, and `edge` in the latest beta version (v1.12.0.0). I haven't made a PR to update them in Oneechan because I'm not sure which uses of them are really needed.

**Comment by nebukazar** [comment]
>I'm also planning on removing the index, thread-view, catalog, and archive classes since 4chan adds is_index, is_catalog, is_arclist to the body itself (ccd0/4chan-x#955), but that's further into the future.

Sounds good but what about `thread-view`, what is replacing that?

**Comment by ccd0** [comment]
You could do
`body:not(.is_index):not(.is_catalog):not(.is_arclist)`
but that might be a bad idea because it will break when new views are added.
I could have 4chan X add a `is_thread` class if we can't get 4chan devs to do it, which would be the best option.

**Comment by ccd0** [comment]
BTW, why does Oneechan do this?

	:root.ua-blink #qr .captcha-container > div > div:first-of-type {
	  overflow-y: hidden !important;
	  overflow-x: hidden !important;
	  padding-right: 0 !important;
	}

4chan X adds the scrollbar (which should be hidden) to work around a bug in Recaptcha where if you press space to activate the checkbox with the keyboard, it scrolls down the page. This reintroduces the bug.

**Comment by ccd0** [comment]
4chan has added `is_thread`. It would be a good idea to wait a week before switching to it so the change can propagate through all the archived threads.

**Comment by nebukazar** [comment]
>This reintroduces the bug.

I don't remember why I added that but I think it was creating a visible scrollbar in the captcha box on my Chrome version.

**Comment by ccd0** [comment]
There is a scrollbar introduced, but the `padding-right: 15px;` in
```
:root.ua-blink #qr .captcha-container > div > div:first-of-type,
:root.ua-edge #qr .captcha-container > div > div:first-of-type {
  overflow-y: scroll;
  overflow-x: hidden;
  padding-right: 15px;
  height: 99%;
  width: 100%;
}
```
is supposed to push it offscreen. Maybe I should just increase it? How much does it take to push it offscreen for you?

**Comment by nebukazar** [comment]
`padding-right: 15px;`

![capture](https://cloud.githubusercontent.com/assets/5222254/18594694/1952013c-7c39-11e6-8645-7f75eb666075.PNG)

`padding-right: 17px;`

![capture2](https://cloud.githubusercontent.com/assets/5222254/18594724/411e254c-7c39-11e6-9023-6b79a701ee20.PNG)

**Comment by ccd0** [comment]
I think I'll up it to 30px. Give it a bit more margin of safety.

**Comment by ccd0** [comment]
https://github.com/ccd0/4chan-x/commit/913aaa1d92b90de97c6e0ade7284e984513c19d2

**Comment by nebukazar** [comment]
Everything's fixed here. Good job.

**Comment by ccd0** [comment]
I see a few remaining:

```
src/css/Options.css::root.catalog blockquote {
src/css/Original.css:.fixed.bottom-header.index body {
src/css/Original.css:.fixed.bottom-header.catalog body {
src/css/Original.css::root.index.bottom-header:not(.autohide) body {
src/css/Original.css:.fixed.top-header.index body {
src/css/Original.css:.fixed.top-header.catalog body {
src/css/Original.css:.fixed.bottom-header.index .bottomCtrl.desktop,
src/css/Original.css:.fixed.top-header.index .bottomCtrl.desktop {
src/css/General.css::root.index div.navLinks {
src/css/Colors.css::root.catalog .button,
src/css/Colors.css::root.catalog .button:hover,
src/css/Colors.css::root.catalog .panel,
```

**Comment by nebukazar** [comment]
Thanks.

**Comment by nebukazar** [comment]
Actually there seems to be a bug when using the 4chanX catalog as it doesn't attach `.is_catalog` when viewing the catalog but always retains `.is_index`.

![capture](https://cloud.githubusercontent.com/assets/5222254/18687288/44e54dae-7f77-11e6-871f-b050f1a596fb.PNG)

**Comment by ccd0** [comment]
`is_index` is correct for the 4chan X catalog. It's running on the index page, not on `/catalog`. 4chan X will add `catalog-mode` to the document when the index is in catalog mode.

If it changed 4chan's `is_index` to `is_catalog`, you couldn't have different CSS for `/catalog`, which has different HTML and native CSS from the index.
