### ISSUE TITLE
gif banners sometimes won't play

### ISSUE THREAD

**Issue by 1motor9** [nebukazar/OneeChan#89]
I'm not sure what the problem is, but even on the default settings sometimes gif banners won't play. If I refresh the page, it might work, but there is inconsistency. I'm using the latest versions for both 4chan-x and oneechan.

**Comment by nebukazar** [comment]
I can't reproduce but there could be a range of issues, connection, browser, addons etc.

Oneechan doesn't do anything to make the gifs stop playing.
