### ISSUE TITLE
Move to Next Thread hotkeys no longer work with ccd0's most recent update.

### ISSUE THREAD

**Issue by Mudrock1** [nebukazar/OneeChan#91]
As the title says, the most recent update of ccd0 seems to have gimped the "to next thread" option when using OneeChan. It is fine without oneechan enabled, so I believe it is a small compatability issue. When attempting to jump to the next thread, it is only capable of jumping to the first two of them. If you scroll down a bit and attempt to jump to the next thread, it is able to jump to the next-most thread, but then is unable to continue jumping. However, going to the previous thread with ctrl up has no issues whatsoever. 

Firefox 48 
Greasemonkey 3.9 
Tested on Arch Linux (49) and Manjaro. 
Edit: Just tested on Windows, happens there as well.

**Comment by nebukazar** [comment]
Bug was introduced in v5.5.42 because of https://github.com/nebukazar/OneeChan/commit/5f3c80bfee36f41ed0e949c2a3ee5bf4f2fe8c6e#diff-1fd5ffbfe07019dd08a7089a95b7b188R98

**Comment by Mudrock1** [comment]
Confirmed for fix with the update. Thanks for the quick fix! Closing.
