### ISSUE TITLE
OneeChan Hiding Advertisements, Despite Being Set Otherwise

### ISSUE THREAD

**Issue by Yaanu** [nebukazar/OneeChan#95]
Despite the checkmarks being set to display all ads[1], OneeChan appears to be blocking advertisements on 4chan. I've checked this against 4chan X[2], and I can confirm it's limited to OneeChan[3].

I'm not sure what to look for in the console to solve this myself, nor would I be able to say WHAT the problem appears to be. I just like the middle ads, and I know that this issue has been happening after a recent update; I'm not sure which update it was exactly.

Screenshots:
[1] - [4chan X + OneeChan, plus OneeChan's settings.](https://i.imgur.com/ZViIvmo.png)
[2] - [Isolated 4chan X.](https://i.imgur.com/AA02kvy.png)
[3] - [Isolated OneeChan.](https://i.imgur.com/1m1L4mP.png)

**Comment by ccd0** [comment]
Can you post your exported 4chan X and OneeChan settings?

**Comment by Yaanu** [comment]
Sure thing.

[http://pastebin.com/zqepmRDY](4chan X Settings.)
[http://pastebin.com/KpLudzgS](OneeChan Settings.)

**Comment by ccd0** [comment]
You need to enable "Show Board Banners".

**Comment by Yaanu** [comment]
Oh, dammit, I never noticed that.
Thank you!
