### ISSUE TITLE
board banner and board name alignment with new version

### ISSUE THREAD

**Issue by nousernamesareleft** [nebukazar/OneeChan#96]
In the new version board banners are outside of the sidebar and centered over the main area instead of centered in the sidebar. Board name is also right aligned in the side bar instead of centered.

Using latest firefox and greasemonkey.

**Comment by nebukazar** [comment]
I got ahead of myself and didn't test every option. Thanks for the bug report.

**Comment by nousernamesareleft** [comment]
Thanks very much for the quick fix!
