### ISSUE TITLE
Cannot install in Google Chrome  version 55.0.2883.87 m (64-bit)

### ISSUE THREAD

**Issue by Arc0re** [nebukazar/OneeChan#98]
Neither drag and droping or double clicking the .crx work. It works on vanilla Chromium though

**Comment by nebukazar** [comment]
It works fine for me on that version. Are you using Tampermonkey? Any console errors?

**Comment by Arc0re** [comment]
I was not using Tampermonkey (and I didn't need to use it before, with 4chanX + OneeChan) and I don't remember any console errors. I'll try again with Tamper
